name: CI

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python for testing
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install Python dependencies
      run:
        python -m pip install -r tests/requirements.txt
    - name: Build
      run: make COVERAGE=1
    - name: Run tests
      run: |
        make tests
        make test_fuzzer
        make test_virtraft
        make gcov
    - name: Upload to codecov
      uses: codecov/codecov-action@v2
